defaults:
  - training
  - _self_

learning_rate: [0.0001, 0.001, 0.01]
batch_size: [16, 32]
optimizer_name: ["adam", "sgd", "adamw"]

checkpoint_save_path: "./model"
model: "hyperparameter_tuning_efficientnet"
epochs: 100
optuna_storage_path: "./mlflow/optuna_hparam_tuning.db"
